### ISSUE TITLE
Install in HACS gives an error

### ISSUE THREAD

**Issue by kilters** [freakshock88/hass-populartimes#3]
I get the following error when installing via HACS. I beleive this is because the requirement repo has been updated. I did adjust the manifest to git+https://github.com/GrocerCheck/LivePopularTimes@master#LivePopularTimes==1.1 but still got the error:

Unable to install package git+https://github.com/GrocerCheck/LivePopularTimes@master#LivePopularTimes==1.1: ERROR: Could not find a version that satisfies the requirement calendar (from LivePopularTimes==1.1) (from versions: none) ERROR: No matching distribution found for calendar (from LivePopularTimes==1.1) WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by kilters** [comment]
Duplicate. Apologies. Closing.

**Comment by brandonolson32** [comment]
What was the solution?
