### ISSUE TITLE
Issue installing via HACS

### ISSUE THREAD

**Issue by kilters** [freakshock88/hass-populartimes#4]
I get the following error when installing via HACS. I beleive this is because the requirement repo has been updated. I did adjust the manifest to git+https://github.com/GrocerCheck/LivePopularTimes@master#LivePopularTimes==1.1 but still got the error:

Unable to install package git+https://github.com/GrocerCheck/LivePopularTimes@master#LivePopularTimes==1.1: ERROR: Could not find a version that satisfies the requirement calendar (from LivePopularTimes==1.1) (from versions: none) ERROR: No matching distribution found for calendar (from LivePopularTimes==1.1) WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

I'm running HA in docker:

version: 2021.1.1
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.4.78-2-pve
arch: x86_64
timezone: Europe/Dublin

GitHub API: ok
Github API Calls Remaining: 4803
Installed Version: 1.9.0
Stage: running
Available Repositories: 771
Installed Repositories: 21

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

dashboards: 1
mode: storage
views: 10
resources: 6

websocket_connection_state: connected
api_endpoint_reachable: ok

**Comment by geoffbon** [comment]
I had all the same issues, uninstalled, and today went to take a look and it doesn't show up in HACS at all for me any more.  
HA 2021.1.4 on docker, HACS 1.10.0.

**Comment by freakshock88** [comment]
I found the issue now and have fixed it. 
The component should still be available from HACS.
Please update and confirm it is working again for you!
