### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by TychoWerner** [freakshock88/hass-populartimes#5]
Hi,

I see this will become a problem in the not so distant future and thought I should bring it to your intention.

 Logger: homeassistant.loader
Source: loader.py:786
First occurred: 21:26:13 (3 occurrences)
Last logged: 21:26:15

No 'version' key in the manifest file for custom integration 'populartimes'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'populartimes'

**Comment by freakshock88** [comment]
Hi,

Thanks for your issue.
I have just fixed the missing version key and published a new version of the integration.
Please update to this new version to fix the issue.
