### ISSUE TITLE
list attribute as the sensor value

### ISSUE THREAD

**Issue by jdohn15** [freakshock88/hass-populartimes#6]
Hello, 

is there a way to get the sensor to list the attribute value as the value instead of the percent?

Say for Monday at 06:00 the attribute value was 6, is there a way to make the value of the sensor 6?

Currently it just lists the popular times as a series [0,0,0,0,....] which is unusable for making graphs. 

![image](https://user-images.githubusercontent.com/78576051/148654923-cb24d47c-10c6-4652-a8ce-5716c848f737.png)

Thanks,

John

**Comment by freakshock88** [comment]
I have now updated the component with these changes: 

* Added fallback to historical Maps data, for when live popularity is not reported for a place.
* Added a new attribute to indicate whether current state is from historical or live data.

If you update (via HACS) to version 0.25 you should see historical data reflect in the sensor's value :)
